### ISSUE TITLE
[OpenBSD] Crashing when attacking/defending

### ISSUE THREAD

**Issue by c64skin** [forkserf/forkserf#115]
Hi! I'm getting Segmentation Faults as per the title, i've used gdb to try get you some useful info:
```
Debug: [serf] Fight: 1024 vs 3705 (1979). Defender winning.
Debug: [serf] Fight: 3705 vs 1024 (764). Attacker winning.
Debug: [serf] inside set_lost_state C, serf of type Serf::TypeKnight4 being set to Lost, dest when it exited Inventory was flag# 120 which has pos 1040
Debug: [game] about to call set_lost_state on serf at pos 1955 case1, map says no flag here
Debug: [serf] inside set_lost_state C, serf of type Serf::TypeKnight4 being set to Lost, dest when it exited Inventory was flag# 120 which has pos 1040
Debug: [game] about to call set_lost_state on serf at pos 1955 case1, map says no flag here
Debug: [serf] Fight: 1024 vs 3705 (3863). Defender winning.
Warning: [serf] inside handle_knight_occupy_enemy_building(), a serf at pos 1890 is being set to StateLost! because Something is wrong
Segmentation fault (core dumped)


(gdb) bt
#0  Building::has_inventory (this=0x0) at /mnt/newdisk1/source/forkserf/src/building.h:212
#1  0x000008a7566236ba in Serf::handle_state_knight_free_walking (this=0x8aa2ae7db80) at /mnt/newdisk1/source/forkserf/src/serf.cc:5588
#2  0x000008a756629b8f in Serf::update (this=0x8aa2ae7db80) at /mnt/newdisk1/source/forkserf/src/serf.cc:6312
#3  0x000008a756563ead in Game::update_serfs (this=0x8a9c70d3418) at /mnt/newdisk1/source/forkserf/src/game.cc:743
#4  0x000008a7565650b2 in Game::update (this=0x8a9c70d3418) at /mnt/newdisk1/source/forkserf/src/game.cc:962
#5  0x000008a75644fa73 in Interface::update (this=0x7f7fffff0ba0) at /mnt/newdisk1/source/forkserf/src/interface.cc:875
#6  0x000008a7564512cb in Interface::handle_event (this=0x7f7fffff0ba0, event=0x7f7fffff0970) at /mnt/newdisk1/source/forkserf/src/interface.cc:1104
#7  0x000008a75663c48b in EventLoop::notify_handlers (this=0x8a7566e88a8 <EventLoop::get_instance()::event_loop>, event=0x7f7fffff0970) at /mnt/newdisk1/source/forkserf/src/event_loop.cc:54
#8  0x000008a75663c7db in EventLoop::notify_update (this=0x8a7566e88a8 <EventLoop::get_instance()::event_loop>) at /mnt/newdisk1/source/forkserf/src/event_loop.cc:124
#9  0x000008a7566425ae in EventLoopSDL::run (this=0x8a7566e88a8 <EventLoop::get_instance()::event_loop>) at /mnt/newdisk1/source/forkserf/src/event_loop-sdl.cc:292
#10 0x000008a7563b9ec9 in main (argc=1, argv=0x7f7fffff12f8) at /mnt/newdisk1/source/forkserf/src/freeserf.cc:163
(gdb) q
```

I'll gladly keep on as a tester if you need one, i really wanna play this game properly.

Thanks.

**Comment by tlongstretch** [comment]
I assume you are using 'stable' branch.

I took a look at the code and I am thinking that a flag was removed, but the handle_state_knight_free_walking code doesn't check if the expected flag & building actually exist?  

building->has_inventory is only called in one place in Serf::handle_state_knight_free_walking,  here's the relevant code:
```

              Flag *dest = game->get_flag(other->s.walking.dest);
              Building *building = dest->get_building();
              if (!building->has_inventory()) {
                building->requested_knight_attacking_on_walk();
              }
```

**Comment by tlongstretch** [comment]
I don't want to blindly push a change here, I will leave this open and try it out and playtest it a bit.  I have to go back and find all the bugfixes from unstable branch and merge them into stable.

**Comment by c64skin** [comment]
Thanks and nice to see you back on the project.

**Comment by tlongstretch** [comment]
Thanks!  I only work on it during winter time, but I will probably never give it up. I feel like I could spend a lifetime refining this game

**Comment by tlongstretch** [comment]
I am looking at this more closely now, and I suspect what is happening is:

- AI player attacks a building and wins
- the attacked building immediately becomes AI player's, but is too far into enemy territory or blocked such that the winning player cannot successfully build a road to connect it to its road network
- the AI burns the hut because it cannot be connected to its road network (this is current AI logic, but maybe needs some improvement!)
- before/while AI knights who just won the fight begin to enter the building to occupy it, it no longer exists and the knights become lost
- I'm not exactly sure why the crash occurs, but I suspect it is related to the building being destroyed as the knights attempt to enter.

**Comment by tlongstretch** [comment]
oh, it seems I already identified and fixed this bug!   and yes it was a failure to check that building is nullptr (i.e. building removed)

I will be pushing a new update to 'stable' very soon that includes this fix. If you want to patch it yourself, apply a nullptr check to the `if (!building->has_inventory){` code to Serf::handle_state_knight_free_walking() in serf.cc

example:
                if(building != nullptr && !building->has_inventory()){

**Comment by tlongstretch** [comment]
fixed in stable_candidate

**Comment by c64skin** [comment]
Thanks, i've tried it out and overtaken several houses without crashing at that exact point.

I'm still getting other crashes at building.h , though since you are coding furiously atm maybe better to hold off with my bugreports until things settle down.

Here's the output:

```
Info: [flag.cc] DEBUG z2 - flag at pos 711, scheduled slot for dir 5 is 0
Debug: [serf] inside set_lost_state A, serf of type Serf::TypeBuilder being set to Lost, dest when it exited Inventory was flag# 37 which has pos 3706
Debug: [game] about to call set_lost_state on serf at pos 122 case1, map says no flag here
Debug: [serf] inside set_lost_state C, serf of type Serf::TypeBuilder being set to Lost, dest when it exited Inventory was flag# 37 which has pos 3706
Debug: [game] about to call set_lost_state on serf at pos 122 case1, map says no flag here
Info: [flag.cc] start of Flag::prioritize_pickup, flag at pos 694, dir 0
Info: [flag.cc] inside Flag::prioritize_pickup, flag at pos 694, dir 0 slot #0 has no dest, skipping special prioritization check
Info: [flag.cc] inside Flag::prioritize_pickup, flag at pos 694, dir 0 slot #0 is currently top priority, res_type Resource::TypePlank, best res_prio so far is 26
[New thread 114699]
[New thread 274592]
[New thread 437093]
[New thread 270874]
[New thread 543915]
[New thread 466776]
[New thread 503979]
[New thread 514431]
[New thread 469072]
[New thread 566417]
[New thread 530929]
[New thread 189403]
[New thread 471849]
[New thread 526731]
[New thread 160684]

Thread 1 received signal SIGSEGV, Segmentation fault.
Building::get_type (this=0x0) at /mnt/newdisk1/source/forkserf/src/building.h:149
149       Type get_type() const { return type; }
(gdb) bt
#0  Building::get_type (this=0x0) at /mnt/newdisk1/source/forkserf/src/building.h:149
#1  0x000008b9a8b31994 in Flag::prioritize_pickup (this=0x8bc68b5cc00, dir=DirectionRight, player=0x8bc8a0a4000) at /mnt/newdisk1/source/forkserf/src/flag.cc:1008
#2  0x000008b9a8b3547f in Flag::reset_transport (this=0x8bbe4b5a400, other=0x8bc68b5cc00) at /mnt/newdisk1/source/forkserf/src/flag.cc:1607
#3  0x000008b9a8b5217e in Game::flag_reset_transport (this=0x8bc1625b418, flag=0x8bbe4b5a400) at /mnt/newdisk1/source/forkserf/src/game.cc:1246
#4  0x000008b9a8b56bf6 in Game::demolish_building_ (this=0x8bc1625b418, pos=3641) at /mnt/newdisk1/source/forkserf/src/game.cc:2061
#5  0x000008b9a8b56eaf in Game::surrender_land (this=0x8bc1625b418, pos=3576) at /mnt/newdisk1/source/forkserf/src/game.cc:2102
#6  0x000008b9a8b5628c in Game::update_land_ownership (this=0x8bc1625b418, init_pos=4089) at /mnt/newdisk1/source/forkserf/src/game.cc:2252
#7  0x000008b9a8b579f7 in Game::occupy_enemy_building (this=0x8bc1625b418, building=0x8bbe4b77100, player_num=0) at /mnt/newdisk1/source/forkserf/src/game.cc:2352
#8  0x000008b9a8c083c9 in Serf::handle_knight_occupy_enemy_building (this=0x8bc45c16900) at /mnt/newdisk1/source/forkserf/src/serf.cc:5664
#9  0x000008b9a8c0f781 in Serf::update (this=0x8bc45c16900) at /mnt/newdisk1/source/forkserf/src/serf.cc:6478
#10 0x000008b9a8b4f8e1 in Game::update_serfs (this=0x8bc1625b418) at /mnt/newdisk1/source/forkserf/src/game.cc:804
#11 0x000008b9a8b50a1c in Game::update (this=0x8bc1625b418) at /mnt/newdisk1/source/forkserf/src/game.cc:1027
#12 0x000008b9a8a2d645 in Interface::update (this=0x7f7fffff1ba8) at /mnt/newdisk1/source/forkserf/src/interface.cc:878
#13 0x000008b9a8a2f974 in Interface::handle_event (this=0x7f7fffff1ba8, event=0x7f7fffff1990) at /mnt/newdisk1/source/forkserf/src/interface.cc:1219
#14 0x000008b9a8c21804 in EventLoop::notify_handlers (this=0x8b9a8cc3b30 <EventLoop::get_instance()::event_loop>, event=0x7f7fffff1990) at /mnt/newdisk1/source/forkserf/src/event_loop.cc:54
#15 0x000008b9a8c21b5b in EventLoop::notify_update (this=0x8b9a8cc3b30 <EventLoop::get_instance()::event_loop>) at /mnt/newdisk1/source/forkserf/src/event_loop.cc:124
#16 0x000008b9a8c2776d in EventLoopSDL::run (this=0x8b9a8cc3b30 <EventLoop::get_instance()::event_loop>) at /mnt/newdisk1/source/forkserf/src/event_loop-sdl.cc:292
#17 0x000008b9a899b810 in main (argc=1, argv=0x7f7fffff23b8) at /mnt/newdisk1/source/forkserf/src/freeserf.cc:184
(gdb) c
Continuing.

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb) q

**Comment by c64skin** [comment]
Close this issue if you want tlongstretch, i'll wait until things settle down in doing further reports. Thanks for the work you do.

**Comment by tlongstretch** [comment]
oh, yeah the 'stable_candidate' branch is currently extremely _unstable_  right now while I change things :)
